# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wasap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wasap
  pod 'Firebase/Analytics'

  target 'WasapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
